apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - github:
        clientID: d49ef20b8d93cf486782
        clientSecret:
          name: github-client-secret
        hostname: ''
        organizations:
          - M-M-Squad
        teams: []
      mappingMethod: claim
      name: github
      type: GitHub
