apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: infra-machine-autoscaler
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name:
