---

- name: AWS playbook
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - amazon.aws
    
  vars:
    region: us-east-2

  tasks:
    - name: Facts block
      tags: always    
      block:
  
      - name: Get VPC facts
        register: vpc_info
        amazon.aws.ec2_vpc_net_info:
          region: "{{ region }}"
          
      - name: Collect VPC ID
        when: vpc_info.vpcs[0] is defined
        ansible.builtin.set_fact:
          aws_vpc_id: "{{ vpc_info.vpcs[0].id }}"
          
      - name: Print VPC ID
        ansible.builtin.debug:
          var: aws_vpc_id
        
      - name: Get subnet facts
        register: subnet_info
        amazon.aws.ec2_vpc_subnet_info:
          region: "{{ region }}"

      - name: Set blank fact
        ansible.builtin.set_fact:
          vpc_subnet_list: []
          
      - name: Collect subnet ids
        when: subnet_info.subnets[0] is defined
        loop: "{{ subnet_info.subnets }}"
        ansible.builtin.set_fact:
          subnet_ids: "{{ vpc_subnet_list }} + [ '{{ item.subnet_id }}' ]"
          
      - name: Print subnet ids
        debug:
          var: subnet_ids
