name: 'Ansible GitHub Actions'
on:
  workflow_dispatch:

jobs:
  Ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run ansible playbook
        run: |
          #ansible-playbook ansible-tasks/main.yml -e "ansible_python_interpreter=`which python3`" 
          ansible-playbook ansible-tasks/main.yml
     

#      - name: Install OpenShift CLI tools
#        uses: redhat-actions/openshift-tools-installer@v1
#        with:
#          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
#          oc: "${{secrets.OCP_CLIENT_VERSION}}"

#      - name: Run ansible playbook
#        run: |
#          cp ocp-artifact/auth/kubeconfig $GITHUB_WORKSPACE/kubeconfig
#          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
#          ansible-playbook ansible-tasks/main.yaml
