name: Deploy OCP 4.x IPI to AWS 
on:
  push:
    branches:
      - 'main'
    paths:
      - 'deploy.md'
jobs:
  Setup:
    name: Setup OpenShift Installer Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Working Directory for OCP Install 
        run: |
          perl -pi -e 's/PULL_SECRET/${{ secrets.PULL_SECRET }}/' install-config.yaml
          mkdir ocp-artifact
          cp install-config.yaml ocp-artifact/
          cat ocp-artifact/install-config.yaml
        
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "4.7.2"
          oc: "4.7.2"
          
      - name: Create OpenShift Cluster
        run: openshift-install create cluster --dir=ocp-artifact/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          
      - name: Save Artifacts for Destroy
        uses: actions/upload-artifact@v2
        with:
          name: ocp-artifact
          path: ocp-artifact
          
      - name: Setup GitHub IDP
        run: |
          export KUBECONFIG=ocp-artifact/auth/kubeconfig
          oc get nodes
          oc create secret generic github-client-secret --from-literal=clientSecret=${{ secrets.CLIENT_SECRET }} -n openshift-config
          oc apply -f idp-oauth.yaml
          oc adm policy add-cluster-role-to-user cluster-admin ${{ secrets.CLUSTER_ADMIN }}
      
      - name: Deploy ArgoCD
        run: |
          export KUBECONFIG=ocp-artifact/auth/kubeconfig
          oc create namespace argocd
          oc apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          oc patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
#          curl -sSL -o ~/ https://github.com/argoproj/argo-cd/releases/download/v1.7.14/argocd-linux-amd64
#          chmod +x argocd
          
