name: Destroy OCP 4.x IPI in AWS 
on:
  push:
    branches:
      - 'main'
    paths:
      - 'destroy.md'
jobs:
  Setup:
    name: Setup OpenShift Installer Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OCP Cluster Artifacts
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: workflow_name.yml
          workflow_conclusion: success  
          branch: master
          name: artifact_name
          path: extract_here
          check_artifacts:  false
        
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "4"
          
      - name: Destroy OpenShift Cluster
        run: openshift-install destroy cluster --dir=ocp-artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
