name: GitOps-Tasks
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  Setup:
    name: GitOps Day2 Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
          oc: "${{secrets.OCP_CLIENT_VERSION}}"
      - name: Download Artifacts from Cluster Deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yaml
          name: ocp-artifact
          path: ocp-artifact
      - name: Get Infra ID
        run: |
          cp ocp-artifact/auth/kubeconfig $GITHUB_WORKSPACE/kubeconfig
          cat ocp-artifact/metadata.json | jq -r .infraID > $GITHUB_WORKSPACE/infraID
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
          export infraID=$GITHUB_WORKSPACE/infraID
          echo $infraID
      
          
      - uses: actions/checkout@main
      - name: Update infra machinesets
        run: |
          export infraID=`cat $GITHUB_WORKSPACE/infraID`
          echo $infraID
          perl -pi -e 's/{{ infraID }}/$infraID/g' infra-machineset.yaml
          perl -pi -e 's/{{ regionID }}/${{ secrets.AWS_REGION }}/g' infra-machineset.yaml
          cat infra-machineset.yaml
          
          
       
#      - name: Checkout GitOps external repo
#        uses: actions/checkout@v2
#        with:
#          repository: r3dact3d/gitops
#          path: gitops-tasks
