name: GitOps-Tasks
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  Setup:
    name: GitOps Day2 Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts from Cluster Deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yaml
          name: ocp-artifact
          path: ocp-artifact
      
      - uses: actions/checkout@main
      - name: Get Infra ID
        run: |
          export infraID=blinker19-08976d
          echo $infraID
          perl -pi -e "s/{{ infraID }}/$infraID/g" infra-machineset.yaml
          perl -pi -e 's/{{ regionID }}/${{ secrets.AWS_REGION }}/g' infra-machineset.yaml
          cat infra-machineset.yaml

       
#      - name: Checkout GitOps external repo
#        uses: actions/checkout@v2
#        with:
#          repository: r3dact3d/gitops
#          path: gitops-tasks
