name: GitOps-Tasks
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  Setup:
    name: GitOps Day2 Tasks
    runs-on: ubuntu-latest
    steps:     
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
          oc: "${{secrets.OCP_CLIENT_VERSION}}"
          
      - name: Download Artifacts from Cluster Deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yaml
          name: ocp-artifact
          path: ocp-artifact

      - name: Create GitOps 
        run: |
          cp ocp-artifact/auth/kubeconfig $GITHUB_WORKSPACE/kubeconfig
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
          oc create -f https://raw.githubusercontent.com/r3dact3d/gitops/main/blinker19/cluster.yaml
      

