name: GitOps-Tasks
on:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  Setup:
    name: GitOps Day2 Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts from Cluster Deploy
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: deploy.yaml
          name: ocp-artifact
          path: ocp-artifact
      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          openshift-install: "${{secrets.OCP_CLIENT_VERSION}}"
          oc: "${{secrets.OCP_CLIENT_VERSION}}"
          
          
      - name: Checkout ocp4-ansible-roles external repo
        uses: actions/checkout@v2
        with:
          repository: r3dact3d/gitops
          path: gitops-tasks
      - name: GitOps Helper
        run: |
          cp ocp-artifact/auth/kubeconfig $GITHUB_WORKSPACE/kubeconfig
          export KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
          export infraID=`oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster`
          echo $infraID
          perl -pi -e 's/AWS_REGION/${{ secrets.AWS_REGION }}/' gitops-tasks/blinker19/cluster.yaml
          perl -pi -e 's/INFRA_ID/${infraID}/' gitops-tasks/blinker19/cluster.yaml
          cat gitops-tasks/blinker19/cluster.yaml

          oc create -f gitops-tasks/blinker19/cluster.yaml -n openshift-gitops
       
